### ISSUE TITLE
Library not in platformio registry

### ISSUE THREAD

**Issue by Sjorsa** [dok-net/ghostl#1]
Hello, I see you've moved some stuff around. I've been used the EspSoftwareSerial library through Platformio and it's been working fine. Today I got an error saying `Warning! Could not install `{'owner': 'dok-net', 'name': 'ghostl', 'version': '^1.0.0'}` dependency for the`EspSoftwareSerial` package`.  

It seems like this sub-library you've made isn't on platformio yet? Would that be possible to do?

**Comment by dok-net** [comment]
I am sorry, but I don't use platformio. Perhaps it picked up ghostl from Arduino's online lib manager, perhaps there is something that has to be done. Could you kindly find out and perhaps take the steps yourself to everyone's advantage? That would be great.

**Comment by dok-net** [comment]
I've done some quick research, and from that, it would seem that for anyone who have platformio fully set up it's as simple as a single command line statement to get a new library that is already complete with manifest and all listed in the online library manager.

**Comment by dok-net** [comment]
Or, perhaps, for out who it is that are submitting EspSoftwareSerial updates, because for sure it's not me. Again, I don't know, but surprisingly platformio online docs make it seem that a new listing request is required for each update. Whereas, Arduino periodically fetches updates on it own.
